"""Illustrative per-answer cost estimation for the chat UI.

The KIT endpoint does not bill us, so there is no real price. To still give a
sense of what a question would cost on a commercial provider, we borrow
OpenRouter's public list price for the equivalent model (see
``data/model_pricing.json``, regenerated by ``scripts/fetch_model_pricing.py``)
and multiply by the prompt/completion token counts. The result is purely
illustrative.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Optional

_PRICING_PATH = Path(__file__).resolve().parent / "data" / "model_pricing.json"

# Prices learned at runtime rather than from the shipped table. The booth
# build lets the presenter pick a chat model from OpenRouter or DeepSeek,
# whose ids are not in ``data/model_pricing.json`` (that file only covers the
# KIT lineup). Those models are really billed, so the per-answer estimate in
# the chat footer must not silently disappear for them. The model picker
# registers the price it is already showing next to the dropdown here, and
# ``get_model_pricing`` consults this registry first.
#
# Process-global on purpose, like the chat model/provider overrides: a price
# registered for a model id is correct for every session in the process, since
# it is keyed by the model id itself and not by who picked it.
_RUNTIME_PRICING: dict[str, dict] = {}


@lru_cache(maxsize=1)
def _load() -> dict:
    try:
        with open(_PRICING_PATH, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {"models": {}}


def register_runtime_pricing(
    model: str,
    prompt_usd_per_token: Optional[float],
    completion_usd_per_token: Optional[float],
) -> None:
    """Teach the estimator the real per-token price of ``model``.

    Called by the demo's model picker for non-KIT (billed) models. A call with
    either rate missing is ignored, so a half-known price never shadows the
    static table with an unusable entry.
    """
    if not model or prompt_usd_per_token is None or completion_usd_per_token is None:
        return
    _RUNTIME_PRICING[model] = {
        "prompt_usd_per_token": float(prompt_usd_per_token),
        "completion_usd_per_token": float(completion_usd_per_token),
        "runtime": True,
    }


def known_models() -> list[str]:
    """Sorted list of KIT model ids present in the pricing table.

    Deliberately unaffected by the runtime registry: callers use this as "the
    KIT models we shipped a price for", not as "everything we can price".
    """
    return sorted(_load().get("models", {}).keys())


def get_model_pricing(model: Optional[str]) -> Optional[dict]:
    """Return the pricing entry for ``model`` if it has usable prices, else None.

    The runtime registry wins over the static table: a price registered from
    the live provider catalog is what the account is actually billed, whereas
    the table holds illustrative OpenRouter list prices for KIT models.
    """
    if not model:
        return None
    runtime = _RUNTIME_PRICING.get(model)
    if runtime and runtime.get("prompt_usd_per_token") is not None:
        return runtime
    entry = _load().get("models", {}).get(model)
    if entry and entry.get("prompt_usd_per_token") is not None:
        return entry
    return None


def estimate_cost_usd(
    model: Optional[str], prompt_tokens: int, completion_tokens: int
) -> Optional[float]:
    """Illustrative USD cost for a single answer, or None if the model is unknown.

    These prices are not what anyone is charged (KIT is free); they come from
    OpenRouter list prices for the equivalent model.
    """
    entry = get_model_pricing(model)
    if not entry:
        return None
    prompt_rate = entry.get("prompt_usd_per_token")
    completion_rate = entry.get("completion_usd_per_token")
    if prompt_rate is None or completion_rate is None:
        return None
    return prompt_tokens * prompt_rate + completion_tokens * completion_rate


def format_cost_usd(cost: Optional[float]) -> Optional[str]:
    """Format a USD amount with precision suited to its magnitude, or None."""
    if cost is None:
        return None
    if cost <= 0:
        return "$0.00"
    if cost < 0.01:
        return f"${cost:.4f}"
    if cost < 1:
        return f"${cost:.3f}"
    return f"${cost:,.2f}"
