"""
Batch Runner for SciQA Benchmark

This script processes questions from the SciQA dataset (handcrafted or autogenerated)
and saves detailed results including metadata for analysis.

Usage:
    python ama_kbqa/agents/sciqa_agent/batch_runner.py --n_questions 10 --seed 42 --dataset handcrafted
    python ama_kbqa/agents/sciqa_agent/batch_runner.py --n_questions 50 --seed 42 --dataset auto --postprocessing llm_judge
"""

from __future__ import annotations
from ama_kbqa.agents.sciqa_agent.agent import SciQAAgent
import os
import sys
import asyncio
import json
import random
import time
import argparse
import csv
import toml
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional
from io import StringIO

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field
from ama_kbqa.config import (
    get_provider_preferences,
    get_chat_client,
    get_chat_model_name,
    get_sciqa_dataset_path,
)

# Load environment variables
load_dotenv(override=True)


# ==============================================================================
# DUAL OUTPUT LOGGER
# ==============================================================================

class DualOutputLogger:
    """Captures console output to both stdout and a file buffer."""

    def __init__(self):
        self.terminal = sys.stdout
        self.log_buffer = StringIO()

    def write(self, message):
        self.terminal.write(message)
        self.log_buffer.write(message)

    def flush(self):
        self.terminal.flush()

    def get_log(self):
        return self.log_buffer.getvalue()

    def clear(self):
        self.log_buffer = StringIO()


# Path configuration
current_file = Path(__file__).resolve()
ama_kbqa_root = current_file.parents[2]
project_root = current_file.parents[3]
sys.path.insert(0, str(ama_kbqa_root))

# ==============================================================================
# CONFIGURATION
# ==============================================================================

COLOR_RED = '\033[91m'
COLOR_GREEN = '\033[92m'
COLOR_YELLOW = '\033[93m'
COLOR_END = '\033[0m'

BATCH_RESULTS_BASE_DIR = project_root / "batch_results" / "sciqa"
BATCH_RESULTS_BASE_DIR.mkdir(parents=True, exist_ok=True)


# ==============================================================================
# PYDANTIC MODELS
# ==============================================================================

class AnswerJudgment(BaseModel):
    """Structured judgment of an answer's correctness and quality."""

    is_correct: bool = Field(
        description="Whether the predicted answer matches the gold answer"
    )

    correctness_reasoning: str = Field(
        description="Explanation of why the answer is correct or incorrect"
    )

    argumentation_quality: str = Field(
        description="Assessment of the agent's reasoning structure"
    )

    argumentation_score: int = Field(
        ge=1, le=5,
        description="Numeric score for argumentation (1-5)"
    )

    suggested_improvement: str = Field(
        description="Suggestion for improvement"
    )


# ==============================================================================
# UTILITY FUNCTIONS
# ==============================================================================

def load_judge_config() -> Dict[str, Any]:
    """Load judge configuration from config.toml."""
    config_path = project_root / "config.toml"
    if not config_path.exists():
        print("[WARNING] config.toml not found, using defaults")
        return {
            "provider": "openrouter",
            "model": "meta-llama/llama-3.3-70b-instruct",
            "temperature": 0.0,
            "chat_model_provider": ""
        }

    try:
        config = toml.load(config_path)
        postprocessing = config.get("postprocessing", {})

        provider = postprocessing.get("judge_provider", "openrouter")
        provider_config = config.get(provider, {})

        judge_model = "meta-llama/llama-3.3-70b-instruct"
        chat_model_provider = postprocessing.get("chat_model_provider", "")

        return {
            "provider": provider,
            "model": judge_model,
            "temperature": postprocessing.get("judge_temperature", 0.0),
            "base_url": provider_config.get("base_url", "https://openrouter.ai/api/v1"),
            "api_key_env": f"{provider.upper()}_API_KEY" if provider != "openrouter" else "OPENROUTER_API_KEY",
            "chat_model_provider": chat_model_provider
        }
    except Exception as e:
        print(f"[WARNING] Failed to load judge config: {e}, using defaults")
        return {
            "provider": "openrouter",
            "model": "meta-llama/llama-3.3-70b-instruct",
            "temperature": 0.0,
            "base_url": "https://openrouter.ai/api/v1",
            "api_key_env": "OPENROUTER_API_KEY",
            "chat_model_provider": ""
        }


def get_next_batch_folder() -> Path:
    """Find the next available batch folder."""
    batch_num = 1
    while True:
        batch_folder = BATCH_RESULTS_BASE_DIR / f"Batch{batch_num:03d}"
        if not batch_folder.exists():
            batch_folder.mkdir(parents=True, exist_ok=True)
            return batch_folder
        batch_num += 1


def load_sciqa_dataset(dataset_type: str = "handcrafted") -> List[Dict[str, Any]]:
    """
    Load the SciQA dataset from CSV files.

    Args:
        dataset_type: Either "handcrafted" or "autogenerated" (or "auto")

    Returns:
        List of questions with metadata
    """
    dataset_path = get_sciqa_dataset_path(dataset_type)
    full_path = project_root / dataset_path / "full dataset.csv"

    if not full_path.exists():
        # Try test.csv as fallback
        full_path = project_root / dataset_path / "test.csv"

    if not full_path.exists():
        raise FileNotFoundError(f"SciQA dataset not found at {full_path}")

    data = []
    with open(full_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Extract relevant columns
            question = row.get("Paraphrase", "").strip()
            if not question:
                question = row.get("Question without context (comparison)", "").strip()

            answer = row.get("Result", "").strip()
            sparql_query = row.get("Machine-readable query", "").strip()
            q_type = row.get("Q Content", row.get("ORKG-based type", "")).strip()
            research_field = row.get("Research field", "").strip()

            if question and answer:
                data.append({
                    "question": question,
                    "answer": answer,
                    "sparql_query": sparql_query,
                    "q_type": q_type,
                    "research_field": research_field,
                    "raw": row
                })

    print(f"[OK] Loaded {len(data)} questions from {dataset_type} dataset")
    return data


def sample_questions(
    data: List[Dict[str, Any]],
    n: int,
    seed: int = 42
) -> List[Dict[str, Any]]:
    """
    Randomly sample n questions from the dataset.

    Args:
        data: Full dataset
        n: Number of questions to sample
        seed: Random seed for reproducibility

    Returns:
        Sampled questions
    """
    random.seed(seed)
    n_sample = min(n, len(data))
    sampled = random.sample(data, n_sample)

    print(f"[OK] Sampled {n_sample} questions with seed={seed}")
    return sampled


def load_from_questionnaire(questionnaire_path: str) -> List[Dict[str, Any]]:
    """
    Load questions from a pre-generated questionnaire JSON file.

    Args:
        questionnaire_path: Path to the questionnaire JSON file

    Returns:
        List of questions in the same format as sample_questions output
    """
    path = Path(questionnaire_path)
    if not path.exists():
        raise FileNotFoundError(f"Questionnaire file not found: {questionnaire_path}")

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    metadata = data.get("metadata", {})
    questions = data.get("questions", [])

    print(f"[OK] Loaded questionnaire from: {questionnaire_path}")
    print(f"     Dataset: {metadata.get('dataset', 'unknown')}")
    print(f"     Generated: {metadata.get('generated_at', 'unknown')}")
    print(f"     Seed: {metadata.get('seed', 'unknown')}")
    print(f"     Questions: {len(questions)}")

    # Transform questionnaire format to match expected structure
    transformed = []
    for q in questions:
        transformed.append({
            "question": q.get("question", ""),
            "answer": q.get("answer", ""),
            "sparql_query": q.get("sparql_query", ""),
            "q_type": q.get("q_type", ""),
            "research_field": q.get("research_field", ""),
            "raw": q.get("raw", {})
        })

    return transformed


def judge_answer_with_llm(
    question: str,
    predicted_answer: str,
    gold_answer: str,
    agent_log: str,
    sparql_query: str = ""
) -> Dict[str, Any]:
    """
    Use LLM to judge whether the predicted answer is correct.

    Args:
        question: The original question
        predicted_answer: The agent's answer
        gold_answer: The ground truth answer
        agent_log: The agent's reasoning log
        sparql_query: The ground truth SPARQL query (optional)

    Returns:
        Judgment dictionary
    """
    judge_config = load_judge_config()

    client = get_chat_client()
    model = judge_config.get("model", get_chat_model_name())

    prompt = f"""You are an expert evaluator for a scientific knowledge graph question-answering system.

## Task
Judge whether the PREDICTED ANSWER correctly answers the question, comparing it to the GOLD ANSWER.

## Question
{question}

## Gold Answer (Ground Truth)
{gold_answer}

## Predicted Answer
{predicted_answer}

## Agent's Reasoning Log (excerpt)
{agent_log[:3000]}...

## Evaluation Criteria
1. **Semantic Equivalence**: Does the predicted answer convey the same information as the gold answer?
2. **Completeness**: Does it answer the full question?
3. **Accuracy**: Is the information factually correct based on what we know?

## Response Format
Respond with a JSON object:
{{
    "is_correct": true/false,
    "correctness_reasoning": "Detailed explanation...",
    "argumentation_quality": "Assessment of reasoning...",
    "argumentation_score": 1-5,
    "suggested_improvement": "Suggestion..."
}}

Respond ONLY with the JSON object."""

    try:
        call_params = {
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a precise answer evaluator. Respond only with valid JSON."},
                {"role": "user", "content": prompt}
            ],
            "temperature": judge_config.get("temperature", 0.0),
            "max_tokens": 1000,
            "response_format": {"type": "json_object"}
        }

        provider_prefs = get_provider_preferences()
        if provider_prefs:
            call_params["extra_body"] = {"provider": provider_prefs}

        response = client.chat.completions.create(**call_params)
        result = json.loads(response.choices[0].message.content)

        return {
            "is_correct": result.get("is_correct", False),
            "correctness_reasoning": result.get("correctness_reasoning", ""),
            "argumentation_quality": result.get("argumentation_quality", ""),
            "argumentation_score": result.get("argumentation_score", 3),
            "suggested_improvement": result.get("suggested_improvement", "")
        }

    except Exception as e:
        print(f"[ERROR] LLM judge failed: {e}")
        return {
            "is_correct": False,
            "correctness_reasoning": f"Judge error: {str(e)}",
            "argumentation_quality": "Unable to assess",
            "argumentation_score": 0,
            "suggested_improvement": "Fix judge errors"
        }


async def process_question(
    agent: SciQAAgent,
    item: Dict[str, Any],
    question_idx: int,
    total_questions: int,
    postprocessing_mode: str = "llm_judge"
) -> Dict[str, Any]:
    """
    Process a single question through the agent.

    Args:
        agent: The SciQA agent instance
        item: Question data
        question_idx: Current question index
        total_questions: Total number of questions
        postprocessing_mode: Evaluation method

    Returns:
        Result dictionary
    """
    question = item["question"]
    gold_answer = item["answer"]
    sparql_query = item.get("sparql_query", "")
    q_type = item.get("q_type", "Unknown")

    print(f"\n{'='*70}")
    print(f"[{question_idx}/{total_questions}] Question: {question[:100]}...")
    print(f"Gold Answer: {gold_answer}")
    print(f"Q Type: {q_type}")
    print(f"{'='*70}")

    # Capture console output
    logger = DualOutputLogger()
    original_stdout = sys.stdout
    sys.stdout = logger

    start_time = time.time()

    try:
        predicted_answer = await agent.ask(question)
        elapsed_time = time.time() - start_time

        sys.stdout = original_stdout
        agent_log = logger.get_log()

        print(f"[ANSWER] {predicted_answer[:200]}...")
        print(f"[TIME] {elapsed_time:.2f}s")

        # Evaluate answer
        is_correct = False
        judgment = None

        if postprocessing_mode == "llm_judge":
            judgment = judge_answer_with_llm(
                question=question,
                predicted_answer=predicted_answer,
                gold_answer=gold_answer,
                agent_log=agent_log,
                sparql_query=sparql_query
            )
            is_correct = judgment.get("is_correct", False)
        else:
            # Simple string matching
            is_correct = gold_answer.lower().strip() in predicted_answer.lower()

        if is_correct:
            print(f"{COLOR_GREEN}[CORRECT]{COLOR_END}")
        else:
            print(f"{COLOR_RED}[INCORRECT]{COLOR_END}")

        # Get token usage and tool stats
        token_usage = agent.token_usage.copy()
        tool_summary = agent.get_tool_call_summary()

        result = {
            "question_idx": question_idx,
            "question": question,
            "gold_answer": gold_answer,
            "predicted_answer": predicted_answer,
            "sparql_query": sparql_query,
            "qtype": q_type,
            "research_field": item.get("research_field", ""),
            "accuracy": is_correct,
            "judgment": judgment,
            "elapsed_time": round(elapsed_time, 2),
            "token_usage": token_usage,
            "tool_summary": tool_summary,
            "agent_log": agent_log[:10000],
            "timestamp": datetime.now().isoformat()
        }

        return result

    except Exception as e:
        sys.stdout = original_stdout
        elapsed_time = time.time() - start_time

        print(f"{COLOR_RED}[ERROR] {str(e)}{COLOR_END}")

        return {
            "question_idx": question_idx,
            "question": question,
            "gold_answer": gold_answer,
            "predicted_answer": f"ERROR: {str(e)}",
            "sparql_query": sparql_query,
            "qtype": q_type,
            "research_field": item.get("research_field", ""),
            "accuracy": False,
            "judgment": None,
            "elapsed_time": round(elapsed_time, 2),
            "token_usage": {},
            "tool_summary": {},
            "agent_log": logger.get_log() if logger else "",
            "error": str(e),
            "timestamp": datetime.now().isoformat()
        }

    finally:
        # Reset agent for next question
        await agent.soft_reset()
        logger.clear()


async def run_batch(
    n_questions: int = 10,
    seed: int = 42,
    dataset_type: str = "handcrafted",
    postprocessing_mode: str = "llm_judge",
    questionnaire_path: Optional[str] = None,
    use_fewshot: bool = True
) -> None:
    """
    Run batch processing on SciQA dataset.

    Args:
        n_questions: Number of questions to process
        seed: Random seed for reproducibility
        dataset_type: "handcrafted" or "autogenerated"
        postprocessing_mode: Evaluation method
        questionnaire_path: Optional path to a pre-generated questionnaire JSON file
        use_fewshot: Whether to inject few-shot examples (set False for ablation)
    """
    print(f"\n{'='*70}")
    print(f"SCIQA BATCH RUNNER")
    if questionnaire_path:
        print(f"Questionnaire: {questionnaire_path}")
    else:
        print(f"Dataset: {dataset_type}")
    print(f"Questions: {n_questions}")
    print(f"Seed: {seed}")
    print(f"Postprocessing: {postprocessing_mode}")
    print(f"{'='*70}\n")

    # Load questions - either from questionnaire or by sampling
    if questionnaire_path:
        sampled = load_from_questionnaire(questionnaire_path)
        # Limit to n_questions if specified
        if n_questions and n_questions < len(sampled):
            sampled = sampled[:n_questions]
            print(f"[OK] Limited to first {n_questions} questions from questionnaire")
    else:
        data = load_sciqa_dataset(dataset_type)
        sampled = sample_questions(data, n_questions, seed)

    # Create batch folder
    batch_folder = get_next_batch_folder()
    print(f"[OK] Results will be saved to: {batch_folder}")

    # Initialize agent
    agent = SciQAAgent(use_fewshot=use_fewshot)
    if not use_fewshot:
        print("[ABLATION] Few-shot examples DISABLED")

    # Process questions
    results = []
    correct_count = 0

    for idx, item in enumerate(sampled, 1):
        result = await process_question(
            agent=agent,
            item=item,
            question_idx=idx,
            total_questions=len(sampled),
            postprocessing_mode=postprocessing_mode
        )
        results.append(result)

        if result.get("accuracy", False):
            correct_count += 1

        # Progress update
        current_accuracy = correct_count / idx * 100
        print(f"[PROGRESS] {idx}/{len(sampled)} | Accuracy: {current_accuracy:.1f}%")

    # Close agent
    await agent.close()

    # Calculate final statistics
    total = len(results)
    accuracy = correct_count / total * 100 if total > 0 else 0

    total_tokens = sum(r.get("token_usage", {}).get("total_tokens", 0) for r in results)
    total_time = sum(r.get("elapsed_time", 0) for r in results)

    # Aggregate tool stats
    tool_totals = {}
    for r in results:
        tool_counts = r.get("tool_summary", {}).get("tool_counts", {})
        for tool, count in tool_counts.items():
            tool_totals[tool] = tool_totals.get(tool, 0) + count

    # Summary
    summary = {
        "batch_id": batch_folder.name,
        "dataset_type": dataset_type if not questionnaire_path else None,
        "questionnaire_path": questionnaire_path,
        "n_questions": total,
        "seed": seed,
        "postprocessing_mode": postprocessing_mode,
        "accuracy": round(accuracy, 2),
        "correct_count": correct_count,
        "total_tokens": total_tokens,
        "total_time_seconds": round(total_time, 2),
        "avg_time_per_question": round(total_time / total, 2) if total > 0 else 0,
        "tool_totals": tool_totals,
        "timestamp": datetime.now().isoformat()
    }

    # Save results
    results_file = batch_folder / "results.json"
    with open(results_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    summary_file = batch_folder / "summary.json"
    with open(summary_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    # Print final summary
    print(f"\n{'='*70}")
    print(f"BATCH COMPLETE")
    print(f"{'='*70}")
    print(f"Accuracy: {accuracy:.1f}% ({correct_count}/{total})")
    print(f"Total Tokens: {total_tokens:,}")
    print(f"Total Time: {total_time:.1f}s")
    print(f"Avg Time/Question: {total_time/total:.1f}s" if total > 0 else "N/A")
    print(f"\nTool Usage:")
    for tool, count in sorted(tool_totals.items(), key=lambda x: x[1], reverse=True):
        print(f"  {tool}: {count}x")
    print(f"\nResults saved to: {batch_folder}")
    print(f"{'='*70}\n")


# ==============================================================================
# MAIN
# ==============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="SciQA Batch Runner",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python batch_runner.py --n_questions 10 --seed 42 --dataset handcrafted
  python batch_runner.py -n 50 --seed 123 --dataset auto --postprocessing llm_judge
  python batch_runner.py --questionnaire db/sciqa_questionnaire.json
        """
    )

    parser.add_argument(
        "-n", "--n_questions",
        type=int,
        default=10,
        help="Number of questions to process (default: 10)"
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42)"
    )

    parser.add_argument(
        "--dataset", "-d",
        type=str,
        choices=["handcrafted", "auto", "autogenerated"],
        default="handcrafted",
        help="Dataset type (default: handcrafted)"
    )

    parser.add_argument(
        "--postprocessing", "-p",
        type=str,
        choices=["llm_judge", "simple"],
        default="llm_judge",
        help="Postprocessing method (default: llm_judge)"
    )

    parser.add_argument(
        "--questionnaire",
        type=str,
        default=None,
        help="Path to a pre-generated questionnaire JSON file (overrides --dataset and --seed sampling)"
    )
    parser.add_argument(
        "--no-fewshot",
        action="store_true",
        default=False,
        help="Disable few-shot example injection (for ablation study)"
    )

    args = parser.parse_args()

    asyncio.run(run_batch(
        n_questions=args.n_questions,
        seed=args.seed,
        dataset_type=args.dataset,
        postprocessing_mode=args.postprocessing,
        questionnaire_path=args.questionnaire,
        use_fewshot=not args.no_fewshot
    ))


if __name__ == "__main__":
    main()
