[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ama-kbqa"
version = "0.1.0"
description = "AMA KBQA"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.53.0",
    "python-dotenv>=1.0.1",
    "tenacity>=9.0.0",
    "fastapi>=0.115.0",
    "uvicorn==0.38.0",  # <-- FEHLENDES KOMMA HIER!
    "openai-agents>=0.5.1",
    "streamlit>=1.51.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ama_kbqa*"]