# docker exec -i virtuoso_ama_kbqa isql 1111 dba kit_ama_kbqa "EXEC=ld_dir('/usr/share/proj', 'kb.nt', 'http://kqapro.org/kb'); rdf_loader_run(); checkpoint;"
#name: ama-db
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7
    container_name: virtuoso_ama_kbqa
    ports:
      # 8890 is the HTTP port (set in virtuoso.ini)
      - "8890:8890"
      # 1111 is the SQL port (set in virtuoso.ini)
      - "1111:1111"

    volumes:
      # 1. Bind mount for the persistent database files
      - ama_virtuoso_data:/database
      # 2. Bind mount for your data to be loaded
      - ./datasets/kqapro:/usr/share/proj
    environment:
      - DBA_PASSWORD=kit_ama_kbqa
      - SPARQL_UPDATE=true

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_ama_kbqa
    ports:
      - 6333:6333
    volumes:
      - ama_qdrant_data:/qdrant/storage

volumes:
  ama_qdrant_data:
  ama_virtuoso_data:
